---
- name: Lesson 01
  hosts: all

  tasks:
    - name: Create base directory
      file:
        path: /tmp/ansible_root
        state: directory

    - name: Download file from Internet
      get_url:
        url: https://ftp.dlink.ru/pub/Switch/DGS-1100-08/Description/DGS-1100-08_A1_B1_QIG_RUS.pdf
        dest: /tmp/ansible_root
        mode: '0440'

    - name: Install packages htop,unzip,telnet,java,python
      yum:
        name: "{{packages}}"
      vars:
        packages:
        - htop
        - unzip
        - telnet
        - java
        - python
      register: result

    - name: Install NGINX
      yum:
        name: nginx
        state: latest
      register: result

    - name: Get http request
      uri:
        url: "curl http://localhost:8080"
        return_content: yes
        status_code: 200
      register: result
